name: Release to GH Packages

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [master]
    types: 
      - completed


jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      
      - name: Create NuGet Package
        working-directory: ./src/Kashyapas.Calendarific.Client
        run: dotnet pack -c Release --version-suffix=${{ steps.slug.outputs.sha8 }}
      
      - name: Archive NuGet Package
        uses: actions/upload-artifact@v1
        with:
          name: Kashyapas.Calendarific.Client
          path: src/Kashyapas.Calendarific.Client/bin/Release/*.nupkg
      
      - name: Archive NuGet Symbols Package
        uses: actions/upload-artifact@v1
        with:
          name: Kashyapas.Calendarific.Client.Symbols
          path: src/Kashyapas.Calendarific.Client/bin/Release/*.snupkg
      
      - name: Publish Nuget to Github Packages
        run: dotnet nuget push **/*.nupkg --source https://nuget.pkg.github.com/lohithgn/index.json