name: Release Preview Package

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [master]
    types: 
      - completed


jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      
      - name: Create NuGet Package
        run: dotnet pack -c Release -o ./packages --version-suffix=${{ steps.slug.outputs.sha8 }} ./src/Kashyapas.Calendarific.Client/Kashyapas.Calendarific.Client.csproj
      
      - name: Publish Nuget to Github Packages
        run: dotnet nuget push ./packages/*.nupkg -k ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json