name: Release Preview Package

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [master]
    types: 
      - completed


jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      
      - name: Create NuGet Package
        run: dotnet pack -c Release -o ./packages --version-suffix=${{format('preview.{0}'.env.GITHUB_RUN_NUMBER)}} ./src/Kashyapas.Calendarific.Client/Kashyapas.Calendarific.Client.csproj
      
      - name: Publish Nuget to Github Packages
        run: dotnet nuget push ./packages/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json